export const CHANGE_CONFIRM_DELETE = "CHANGE_CONFIRM_DELETE";
export const CHANGE_POST = "CHANGE_POST";
export const CHNAGE_ID = "CHNAGE_ID";
export const CHANGE_HEADING = "CHANGE_HEADING";
export const CHANGE_POST_CONTENT = "CHANGE_POST_CONTENT";
export const CHANGE_PHOTO = "CHANGE_PHOTO" ;
export const CHANGE_IS_CLICK_MORE = "CHANGE_IS_CLICK_MORE";
export const CHANGE_ONE_POST = "CHANGE_ONE_POST";


export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";
export const CHANGE_ALL_POST = "CHANGE_ALL_POST";
export const CHANGE_ERR_MESSAGE = "CHANGE_ERR_MESSAGE";


export const CHANGE_SIGNUP_NAME = "CHANGE_SIGNUP_NAME";
export const CHANGE_SIGNUP_EMAIL = "CHANGE_SIGNUP_EMAIL";
export const CHANGE_SIGNUP_PASSWORD = "CHANGE_SIGNUP_PASSWORD";
export const CHANGE_SIGNUP_ERR = "CHANGE_SIGNUP_ERR";



export const CHANGE_SIGNIN_PASSWORD = "CHANGE_SIGNIN_PASSWORD";
export const CHANGE_SIGNIN_EMAIL = "CHANGE_SIGNIN_EMAIL";
export const CHANGE_SIGNIN_ERR = "CHANGE_SIGNIN_ERR";
export const CHANGE_AUTH_STATUS = "CHANGE_AUTH_STATUS";



export const CHANGE_MESSAGE_NAME = "CHANGE_MESSAGE_NAME";
export const CHANGE_MESSAGE_EMAIL = "CHANGE_MESSAGE_EMAIL";
export const CHANGE_MESSAGE_PHONE = "CHANGE_MESSAGE_PHONE";
export const CHANGE_MESSAGE_SUBJECT = "CHANGE_MESSAGE_SUBJECT";
export const CHANGE_MESSAGE_MESSAGE = "CHANGE_MESSAGE_MESSAGE";



export const CHANGE_ALL_MESSAGES = "CHANGE_ALL_MESSAGES";
export const PREVIOUS_MESSAGE_READ = "PREVIOUS_MESSAGE_READ";
export const CHANGE_UNREAD_MESSAGES_COUNT = "CHANGE_UNREAD_MESSAGES_COUNT";


export const CHANGE_SHOW_MESSAGE = "CHANGE_SHOW_MESSAGE";
